### ISSUE TITLE
love.graphics.drawq was removed and is now just love.graphics.draw in LÖVE 0.9.0

### ISSUE THREAD

**Issue by sharno** [kikito/love-tile-tutorial#1]
https://love2d.org/wiki/love.graphics.drawq
http://love2d.org/wiki/love.graphics.draw

**Comment by kikito** [comment]
Yes, you are right.

I don't have the time to do this right now, but I accept pull requests ;)

**Comment by TheDerek** [comment]
I've fixed this issue in pull request #3.
